name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
            java-version: '12.x' 
            distribution: 'adopt'
        env:
            JAVA_HOME: ${{ env.JAVA_HOME }}
      
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - run: flutter pub get

        name: Build APK & IPA file
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
        #- run: flutter test
        #- run: flutter test --coverage
        #- name: Flutter Analyze
        # run: flutter analyze

      - name: Build Android App
        run: flutter build appbundle
        
      - name: Build iOS App
        run: flutter build ios --no-codesign
      - name: Create IPA file
        run: |
            cd build/ios/iphoneos
            mkdir Payload
            cd Payload
            ln -s ../Runner.app
            cd ..
            zip -r app.ipa Payload
              
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with: 
            artifacts: "build/ios/iphoneos/app.ipa"
            tag: "refs/tags/v1.0.${{ github.run_number }}"
            token: ${{ secrets.GHUB_TOKEN }}
